### ISSUE TITLE
Reenable transitions when getThumbBoundsFn is provided

### ISSUE THREAD

**Issue by cpmsmith** [andi34/PhotoSwipe#10]
It looks like this was changed in the partial incorporation of dimsemenov/PhotoSwipe#1455, and is an improvement when the image isn't transitioning back to a thumbnail, but the existing version was better in cases with thumbnails. When a `getThumbBoundsFn` function is provided, the image doesn't snap back to the centre of the screen, and the transition works just fine.

![photoswipe-demo](https://user-images.githubusercontent.com/9437625/98302383-46e08800-1f8a-11eb-84e5-3044ffff58c7.gif)

**Comment by andi34** [comment]
Hey and thanks for your suggestion. I'll think about it 👍

**Comment by andi34** [comment]
Duplicate of https://github.com/andi34/PhotoSwipe/issues/6
