### ISSUE TITLE
question: does loop work in this fork ?

### ISSUE THREAD

**Issue by jueldo** [andi34/PhotoSwipe#11]
in normal version you couldnt disable loop with arrows on desktop, is it here? i forgot whcih PR was it, but i saw discussions about it

**Comment by jueldo** [comment]
ok, it seems to be disables here, but is it enablable? i tried loop:true, in options but it didnt worked?,

**Comment by andi34** [comment]
https://github.com/andi34/PhotoSwipe/commit/ae20d0e90c358a224863bdfab9fa7456fd4fc4d6

You might need to have the history module enabled.

**Comment by andi34** [comment]
You need to set `loop: false,` to disable it.

https://codepen.io/andi34/pen/qBZRxgv
