### ISSUE TITLE
dysfunctional pull/1455

### ISSUE THREAD

**Issue by mjau-mjau** [andi34/PhotoSwipe#6]
Hi. First of all, excellent work on this updated branch of Photoswipe!

Just a note regarding the fix for **"Don't animate "out" when picture was dragged vertically"**:
https://github.com/dimsemenov/PhotoSwipe/pull/1455

It seems a bit dysfunctional, as it now **always** blocks images from zooming back to their respective position on _verticalDragInitiated close. The fix doesn't take into consideration when `getThumbBoundsFn` returns a value. I could probably look into it, but it's a bit beyond my capabilities right now:

Original:
`var duration = out ? _options.hideAnimationDuration : _options.showAnimationDuration;`

#1455 fix
`// Don't animate "out" when picture was dragged vertically
// otherwise use configured in/out duration
var duration;
if ((_verticalDragInitiated || _zoomStarted) && out) {
  duration = 0;
} else {
  duration = out ? _options.hideAnimationDuration : _options.showAnimationDuration;
}`

Personally, I decided to revert the code to original for now.

**Comment by mjau-mjau** [comment]
This could be a better fix?
https://github.com/dimsemenov/PhotoSwipe/pull/1563

**Comment by andi34** [comment]
Hey and thanks a lot for your feedback. I'll take a look at it again once I've some more time, private life is a little bit complicated atm

**Comment by andi34** [comment]
> It looks like this was changed in the partial incorporation of [dimsemenov#1455](https://github.com/dimsemenov/PhotoSwipe/pull/1455), and is an improvement when the image isn't transitioning back to a thumbnail, but the existing version was better in cases with thumbnails. When a `getThumbBoundsFn` function is provided, the image doesn't snap back to the centre of the screen, and the transition works just fine.
> 
> ![photoswipe-demo](https://user-images.githubusercontent.com/9437625/98302383-46e08800-1f8a-11eb-84e5-3044ffff58c7.gif)

**Comment by andi34** [comment]
> This could be a better fix?
> [dimsemenov#1563](https://github.com/dimsemenov/PhotoSwipe/pull/1563)

That one was merged already ( https://github.com/andi34/PhotoSwipe/commit/251e7032a54f9b2659c6551f33b7af84640e4c56 )

Revert pushed:
- https://github.com/andi34/PhotoSwipe/commit/ad2a81b3d08ea3a48bb3a8b454012ca8cd14de48
- https://github.com/andi34/PhotoSwipe/commit/abc63aba5ba95c1474350cf949646c30a6785570
