### ISSUE TITLE
Include the following pull request?

### ISSUE THREAD

**Issue by BARNZ** [andi34/PhotoSwipe#8]
Thanks very much for the fixes you have included in this fork.

Would you be able to also include this pull request?

https://github.com/dimsemenov/PhotoSwipe/pull/1371

It should fix the viewer glitching out in firefox when swiping to close the image and you happen to drag outside of the browser window.

**Comment by andi34** [comment]
Thanks for your suggestion, I'll take a look at it once I've more time again

**Comment by andi34** [comment]
https://github.com/andi34/PhotoSwipe/commit/a44b7a3e0b3b567b6e90c7405df266534a088af5

Added, atm you only have to generate the dist files yourself (until I've updated them too)
